version: "3.8"
services:
  postgres:
    container_name: hotdeals_postgres-dev
    volumes:
      - dev-postgres-hotdeals:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    container_name: hotdeals_redis-dev
    ports:
      - "127.0.0.1:6379:6379"

  scraper:
    container_name: hotdeals_scraper-dev
    environment:
      - DEV

  mailer:
    container_name: hotdeals_mailer-dev
    environment:
      - DEV

  notifier:
    container_name: hotdeals_notifier-dev
    environment:
      - DEV

  backend:
    container_name: hotdeals_backend-dev
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    container_name: hotdeals_frontend-dev
    environment:
      - NODE_ENV=development
    ports:
      - "127.0.0.1:3000:3000"

  proxy:
    container_name: hotdeals_proxy-dev
    ports:
      - "127.0.0.1:4000:80"

volumes:
  dev-postgres-hotdeals:
    external:
      name: dev-postgres-hotdeals
