version: '3.8'
services:
  postgres:
    container_name: hotdeals_postgres-dev
    volumes:
      - dev-postgres-hotdeals:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"

  scraper:
    container_name: hotdeals_scraper-dev
    environment:
      - DEV

  mailer:
    container_name: hotdeals_mailer-dev
    environment:
      - DEV

volumes:
  dev-postgres-hotdeals:
    external:
      name: dev-postgres-hotdeals
