version: '3.8'
services:
  hotdeals_postgres:
    container_name: hotdeals_postgres-dev
    volumes:
      - dev-postgres-hotdeals:/var/lib/postgresql/data/
    ports:
      - 5432

  hotdeals_scraper:
    container_name: hotdeals_scraper-dev
    environment:
      - DEV
    depends_on:
      - hotdeals_postgres

  hotdeals_mailer:
    container_name: hotdeals_mailer-dev
    environment:
      - DEV
    depends_on:
      - hotdeals_postgres

volumes:
  dev-postgres-hotdeals:
    external:
      name: dev-postgres-hotdeals

