version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_NONROOT_DB
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - POSTGRES_NONROOT_DB
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - SCRAPER_HC_UUID
      - TZ=America/Montreal
    depends_on:
      - postgres

  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    environment:
      - MAILER_HC_UUID
      - POSTGRES_NONROOT_DB
      - POSTGRES_NONROOT_PASSWORD
      - POSTGRES_NONROOT_USER
      - SENDGRID_API_KEY
      - SENDGRID_TEMPLATE
      - TZ=America/Montreal
    depends_on:
      - postgres
