#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER ${POSTGRES_NONROOT_USER} WITH PASSWORD '${POSTGRES_NONROOT_PASSWORD}';
		CREATE DATABASE ${POSTGRES_NONROOT_DB} OWNER ${POSTGRES_NONROOT_USER} ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_NONROOT_DB} TO ${POSTGRES_NONROOT_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_NONROOT_USER" --dbname "$POSTGRES_NONROOT_DB" <<-EOSQL
		CREATE TABLE subscribers (
			id SERIAL PRIMARY KEY,
			name TEXT,
			email TEXT NOT NULL UNIQUE
			confirmed BOOLEAN NOT NULL DEFAULT FALSE
		);

		CREATE TABLE threads (
			id INTEGER PRIMARY KEY,
			title TEXT NOT NULL,
			link TEXT NOT NULL,
			posts INTEGER NOT NULL,
			votes INTEGER NOT NULL,
			views INTEGER NOT NULL,
			date_posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
			seen BOOLEAN NOT NULL DEFAULT FALSE
			notified BOOLEAN NOT NULL DEFAULT FALSE
		);
EOSQL
